local Constants = {
	WINDOW_WIDTH = 600,
	WINDOW_HEIGHT = 400,
	BAR_WIDTH = 150,
	BAR_HEIGHT = 10,
	BAR_PADDING = 15,
	STATS_X = 20,
	STATS_Y = 310, -- WINDOW_HEIGHT - 90
	STATUS_BOX_PADDING = 15, -- New constant for internal status box padding
	BUTTON_WIDTH = 80,
	BUTTON_HEIGHT = 25,
	BUTTON_PADDING = 10,
	BUTTONS_START_X = 500, -- WINDOW_WIDTH - 100
	BUTTONS_START_Y = 50,
}
return Constants
